### ISSUE TITLE
Chapter04 pic_carver byte vs string

### ISSUE THREAD

**Issue by headbug** [EONRaider/blackhat-python3#13]
When I run pic_carver.py the packet[TCP].payload returns a byte object, like b'\r\n' and so on. str(packet[TCP].payload) becomes '\\\r\\\n' and thus the following if-conditions evaluate to False.

Also, if the pictures and faces directories do not exists the output fails.

I have made some changes so it runs for me, but I'm a junior python coder so there might be some un-pythonic things going on. Please have a look.

And Thank you for the nice upload.
[pic_carver.py.gz](https://github.com/EONRaider/blackhat-python3/files/7659337/pic_carver.py.gz)

**Comment by EONRaider** [comment]
Ok. Could you make a pull request instead? If the code is right I can simply merge it.
