### ISSUE TITLE
missing netcat.py in chapter02

### ISSUE THREAD

**Issue by JohannPally** [EONRaider/blackhat-python3#16]
I'm trying to debug an error with the pipelined argument example in chapter two `echo -ne "GET / HTTP/1.1\r\nHost: reachtim.com\r\n\r\n" |python ./netcat.py -t reachtim.com -p 80` but could not find a netcat.py file to compare in this repository.

**Comment by JohannPally** [comment]
spotted bhnet.py

**Comment by EONRaider** [comment]
Ok!
