### ISSUE TITLE
error installing github3.py

### ISSUE THREAD

**Issue by merrick424** [EONRaider/blackhat-python3#3]
The original code that Blackhat Python used was python 2.7. Now i get an error when installing github3.py
![error installing github3 py](https://user-images.githubusercontent.com/45082615/83892339-8a557280-a71c-11ea-8310-0df92c7355ff.png)
 on python3. How do we resolve this issue?

**Comment by EONRaider** [comment]
From the look of it it does seem you have some sort of connection issue. I don't think its related to the package at all. The documentation for the library is here: https://github3.readthedocs.io/en/master/

I just installed it using `pip install github3.py` and it worked fine.
