### ISSUE TITLE
Socket close statement missing in 2 files.

### ISSUE THREAD

**Issue by Galen-dp** [EONRaider/blackhat-python3#8]
Hi. I have been comparing your code with other python 3 rewrites and the code in the prerelease pdf for the new 2nd edition of Black Hat Python. I noticed that in your chapter 2 versions of the udp-client.py and tcp-client.py files you don't call client.close() at the end of the file. I know the call is technically not needed as this programs are ending anyway. However since they are intended to be examples of how to write network code shouldn't the client.close() still be included?

**Comment by EONRaider** [comment]
Thanks for reporting that. I just issued a fix in [this commit](https://github.com/EONRaider/blackhat-python3/commit/76db84d1f989113a4bd4038bbe691e6610075815)
